package com.usee.scanner.core

// Generated by android/tools/upstream_contract.py from the RuView sources.
// Do not edit by hand: run `python3 android/tools/upstream_contract.py --update`.

/** Wire-level values shared with RuView firmware and the sensing server. */
object UpstreamContract {
    const val CSI_MAGIC = 0xC5110001L
    const val CSI_HEADER_SIZE = 20
    const val VITALS_MAGIC = 0xC5110002L
    const val FUSED_MAGIC = 0xC5110004L

    const val ESP32_UDP_PORT = 5005
    const val ESP32_STATUS_PORT = 8032
    const val ESP32_STATUS_PATH = "/ota/status"

    const val SERVER_HTTP_PORT = 8080
    const val SERVER_WS_PORT = 8765
    const val SERVER_WS_PATH = "/ws/sensing"
    const val SERVER_HEALTH_PATH = "/health"

    const val MDNS_SERVICE_TYPE = "_ruview._tcp."
}
